### ISSUE TITLE
My items are being deleted

### ISSUE THREAD

**Issue by Fresh-02** [tyfon7/AutoDeposit#1]
To preface, I'm using spt  3.8.0 so that may have something to do with it. However, I have an issue of items being deleted. The only time this occurs is when I sort items that don't have any previous items in a container. When I have some of the same items already in the container this mod works as intended.

**Comment by tyfon7** [comment]
Any other client mods installed?

**Comment by tyfon7** [comment]
And, I have to ask, you're *100%* sure the items are being deleted and not just in a different container you haven't checked?

**Comment by Fresh-02** [comment]
My apologies, I had double checked and thought I went through everything before submitting this. I did a sample test with some injectors before i did a whole back pack. I triple checked everything and found the injectors. They were being transferred to a rig I had stored in backpacks. So the mod seems to be working great as of now :)
