### ISSUE TITLE
Function request

### ISSUE THREAD

**Issue by reysonk** [tyfon7/AutoDeposit#2]
it is required to move everything from the "bag" on the left to the root of the stash on the right by pressing the modifier button (for example ctrl) + click

thank you!

**Comment by reysonk** [comment]
For example there is already such a function, but it is implemented as pulling everything out of a container or backpack. It may be possible to reduce the code :) Thank you for your hard work.

UserInterfaceElements.cs
`166: child.GetComponent<TextMeshProUGUI>().text = "\u21e7T/O";`

https://github.com/reysonk/Inventory-Organizing-Features/blob/main/UI/UserInterfaceElements.cs

**Comment by tyfon7** [comment]
Not what I'm going for with autodeposit. But maybe the multi-select features in UIFixes coming soon will solve this for you

**Comment by reysonk** [comment]
> Not what I'm going for with autodeposit. But maybe the multi-select features in UIFixes coming soon will solve this for you

And yet it would be a good feature, multi-selection will not provide such a solution to the problem.
The usage scenario is as follows:
1. Click on auto deposit to transfer things to containers where there is already the same.
2. The remains of things by ctrl + click and drop to the stash "in 1 click" for further analysis in the "right person"

**Comment by tyfon7** [comment]
Folding my laundry would also be a good feature, but not what this mod is doing :)
