### ISSUE TITLE
Auto Deposit icon has vanished

### ISSUE THREAD

**Issue by TiredRats** [tyfon7/AutoDeposit#3]
Last night I was playing and I spent a long time organizing my stash and using auto deposit. Worked fine no issues. Logged back on this morning before work and the icon was just gone? I don't have any logs due to me closing the server after I got off. Not really sure what would even cause it.

**Comment by tyfon7** [comment]
I'd need the client log, not the server log anyway. If it happens again, hit F12, and click the show log button.

Also make sure you're on latest, 3.0.1 fixed an error where it wouldn't show after raid.

**Comment by tyfon7** [comment]
Closing - in lieu of any response, I'm assuming this was from pre-3.0.1
